// <auto-generated />
using HexaLingo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HexaLingo.Migrations
{
    [DbContext(typeof(HexaLingoDbContext))]
    [Migration("20231122170630_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HexaLingo.Models.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishLang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrenchLang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GermanishLang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<string>("ItalianishLang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PolishLang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SentenceEnglishLang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SentenceFrenchLang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SentenceGermanishLang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SentenceItalianishLang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SentencePolishLang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SentenceSpanishLang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpanishLang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Words");
                });
#pragma warning restore 612, 618
        }
    }
}
